name: Generate and Deploy Resume

on:
  push:
    branches:
      - main # или master
    paths:
      - "resume.json"

  workflow_dispatch:
    inputs:
      theme:
        description: "Выберите шаблон (тему) для рендеринга"
        required: true
        default: "jsonresume-theme-stackoverflow-ru"
        type: choice
        options:
          - jsonresume-theme-stackoverflow-ru
          - jsonresume-theme-eloquent-ru
          - jsonresume-theme-flat
          - jsonresume-theme-even

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

# Добавляем права на запись в репозиторий и публикацию на Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Предотвращает конфликты при одновременных деплоях
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачивание кода
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      # 3. Установка основных зависимостей
      - name: Install core dependencies
        run: npm ci

      # 4. Установка выбранной темы
      - name: Install selected theme
        run: |
          THEME="${{ inputs.theme }}"
          if [ -z "$THEME" ]; then
            THEME="jsonresume-theme-stackoverflow-ru"
          fi
          echo "Используется тема: $THEME"
          echo "THEME=$THEME" >> $GITHUB_ENV
          npm install --no-save $THEME

      # 5. Подготовка папки для публикации сайта
      - name: Prepare build directory
        run: mkdir public

      # 6. Рендеринг HTML веб-страницы
      - name: Export HTML
        run: npx resumed render -o public/index.html -t $THEME

      # 7. Генерация PDF
      - name: Export PDF
        run: npx resumed export -o public/resume.pdf -t $THEME --puppeteer-arg="--no-sandbox" --wait-until networkidle0

      # 8. Сохранение PDF обратно в ветку репозитория
      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/resume.pdf
          if git diff --cached --quiet; then
            echo "PDF не изменился"
          else
            git commit -m "chore: auto-generate resume.pdf with $THEME [skip ci]"
            git push
          fi

      # 9. Загрузка папки public как артефакта для GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public"

      # 10. Публикация сайта на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
